sudo: false
language: node_js
node_js:
  - "0.12"
  - "0.10"
  - 4
  - 5

# Make sure we have new NPM.
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm
  - npm config set loglevel warn

before_script:
  - npm install -g grunt-cli

script:
  - grunt
